#!/bin/bash

echo "Fetching resources from Git Large File Storage..."
pip install git-lfs
python -m git_lfs -v ~/git/$OPENSHIFT_APP_NAME.git $OPENSHIFT_REPO_DIR

echo "Removing unnecessary files..."
cd $OPENSHIFT_REPO_DIR
rm -rf Makefile pytest.ini requirements_*.txt *.env *.md *.sh sql/ tests/
