#!/bin/bash -eu

# http://docs.gunicorn.org/en/stable/signals.html
function get_pid() { cat $OPENSHIFT_DATA_DIR/gunicorn.pid || true }
pid=$(get_pid)
if [ ! -z "$pid" ]; then
    echo "Gracefully restarting gunicorn..."
    kill -s SIGUSR2 $pid
    sleep 1
    if [ -z "$(get_pid)" ]; then sleep 9; fi
    if [ -z "$(get_pid)" -o "$(get_pid)" = "$pid" ]; then
        echo "Gunicorn has failed to start a new process, you need to fix that!"
    else
        kill -s SIGWINCH $pid
        ( sleep 30 && kill -s SIGTERM $pid ) &
    fi
fi
