BEGIN;
    ALTER TABLE paydays ALTER COLUMN nparticipants      SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ntippers           SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ntips              SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ntransfers         SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN transfer_volume    SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ncc_failing        SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ncc_missing        SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ncharges           SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN charge_volume      SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN charge_fees_volume SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN nachs              SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ach_volume         SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN ach_fees_volume    SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN nach_failing       SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN npachinko          SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN pachinko_volume    SET NOT NULL;
    ALTER TABLE paydays ALTER COLUMN nactive            SET NOT NULL;
END;
